### ISSUE TITLE
can't compile on osx 10.11

### ISSUE THREAD

**Issue by olilarkin** [gperciva/artifastring#6]
despite having both /usr/local/lib/libfftw3.a and /opt/local/lib/libfftw3.a I get the error

checking for main in -lfftw3f... no
configure: error: requires libfftw3

**Comment by nickbailey** [comment]
Maybe it requires shared fftw3 (fftw3.so)? not at my computer right now. maybe Graham will tell you.

Sent from my HTC

----- Reply message -----

**Comment by gperciva** [comment]
Do you have

```
/usr/include/fftw3/
```

?  There will be more information in config.log.  (also, technically it requires `fftwf` with a final `f`, but I suspect it's an issue of not having the development headers.)

**Comment by olilarkin** [comment]
thanks, had to build fftw with ./configure --enable-float
